INSERT INTO ADMIN (NAME, EMAIL, PASSWORD) VALUES ('Admin', 'admin@sk.com', '1234');

INSERT INTO COURSE (NAME, ADMIN_ID) VALUES ('Lv3 Intensive Course', 1);

INSERT INTO INSTRUCTOR (NAME) VALUES ('Emily');

INSERT INTO SUBJECT (NAME, COURSE_ID, BUILDING, FLOOR, ROOM_NO, INSTRUCTOR_ID) VALUES ('Agile', 1, '판교캠퍼스 B', '3', '301', 1);
INSERT INTO SUBJECT (NAME, COURSE_ID, BUILDING, FLOOR, ROOM_NO, INSTRUCTOR_ID) VALUES ('MSA', 1, '판교캠퍼스 B', '3', '301', 1);

INSERT INTO TEAM (NAME) VALUES ('A');
INSERT INTO TEAM (NAME) VALUES ('B');

INSERT INTO MEMBER (NAME, TEAM_ID, ROLE, EMAIL, MOBILE) VALUES ('Tim', 1, 'ScrumMaster', 'tim@sk.com', '010-1234-0001');
INSERT INTO MEMBER (NAME, TEAM_ID, ROLE, EMAIL, MOBILE) VALUES ('Mary', 1, 'Member', 'mary@sk.com', '010-4321-0001');

INSERT INTO ATTENDANCE (COURSE_ID, MEMBER_ID) VALUES (1, 1);
INSERT INTO ATTENDANCE (COURSE_ID, MEMBER_ID) VALUES (1, 2);