drop table if exists admin CASCADE;
drop table if exists attendance CASCADE;
drop table if exists course CASCADE;
drop table if exists instructor CASCADE;
drop table if exists subject CASCADE;
drop table if exists trainee CASCADE;
drop table if exists member CASCADE;
drop table if exists team CASCADE;

create table admin (
    id bigint generated by default as identity,
    name varchar(255),
    email varchar(255),
    password varchar(255),
    primary key (id)
);

create table attendance (
    id bigint generated by default as identity,
    course_id bigint,
    member_id bigint,
    primary key (id)
);

create table course (
    id bigint generated by default as identity,
    admin_id bigint,
    name varchar(255),
    primary key (id)
);

create table instructor (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table subject (
    id bigint generated by default as identity,
    name varchar(255),
    building varchar(255),
    floor varchar(255),
    room_no varchar(255),
    course_id bigint,
    instructor_id bigint,
    primary key (id)
);

create table member (
    id bigint generated by default as identity,
    name varchar(255),
    role varchar(255),
    email varchar(255),
    mobile varchar(255),
    team_id bigint,
    primary key (id)
);

create table team (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table attendance 
   add constraint FKmwxjtpjcf6y7m8x2jqeryj255 
   foreign key (course_id) 
   references course;

alter table attendance 
   add constraint FKghlbinj34ic6pwlx2nv1largn 
   foreign key (member_id) 
   references member;
   
alter table course 
   add constraint FK24rir1do7hc0pocea8yi4orn3 
   foreign key (admin_id) 
   references admin;
    
alter table subject 
   add constraint FKnxhd764cm1ie783v26t3jsdlx 
   foreign key (course_id) 
   references course;
    
alter table subject 
   add constraint FKs18sipygps4106j8mxftfmfg6 
   foreign key (instructor_id) 
   references instructor;
       
alter table member 
   add constraint FKcjte2jn9pvo9ud2hyfgwcja0k 
   foreign key (team_id) 
   references team;