spring:
  application: 
    name: edu-monolithic
  profiles: 
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
   console:
      enabled: true
      path: /h2-console
server:
  port: 8080
       
logging:
  level:
    '[com.factory.samples.edu.monolithic]': debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:sql/**/*.xml
  type-aliases-package: com.factory.samples.edu.monolithic.domain.model
